# =========================
# Dockerfile - Sviluppo
# =========================
FROM python:3.11-slim

# per disabilitare buffering dei logs
ENV PYTHONUNBUFFERED=1
ENV APP_ENV=dev
ENV MODEL_VERSION=v2

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiamo solo i modelli (il codice sarà montato come bind mount)
COPY src/ ./src
COPY models/ ./models

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
