experiment_name: "multinomial_nb_v2"

dataset:
  path: "data/lang_detection.csv"
  keep_languages: ["English", "Spanish", "French", "Italian"]
  text_column: "Text"
  label_column: "Language"

model:
  params:
    alpha: 1.0

vectorizer:
  params:
    ngram_range: !!python/tuple [1, 2]   # YAML nativo: tuple vere, non stringhe
    max_df: 0.95
    min_df: 1

grid_search:
  enabled: true
  cv_folds: 5
  metric: "accuracy"
  n_jobs: 1 # evita warning multiprocess su macOS
  param_grid:
    vectorizer__ngram_range:
      - !!python/tuple [1, 1]
      - !!python/tuple [1, 2]
    vectorizer__max_df: [0.9, 0.95, 1.0]
    vectorizer__min_df: [1, 2]
    clf__alpha: [0.5, 1.0, 1.5]

output:
  model_dir: "models/text/language_classification/v2"
  results_file: "results/train_multinb_v2.json"
  model_filename: "best_classifier.pkl"
  label_enc_filename: "label_encoder.pkl"
